
const char *opcode_str[] =
    {
        "EMPTY    ",
        "UND      ",
        "NOP      ",
        "SET      ",
        "CPY      ",
        "JMP      ",
        "ADD      ",
        "SUB      ",
        "XOR      ",
        "OR       ",
        "AND      ",
        "SLL      ",
        "SRL      ",
        "SRA      ",
        "SLT      ",
        "SLTU     ",
        "ADDI     ",
        "XORI     ",
        "ORI      ",
        "ANDI     ",
        "SLLI     ",
        "SRLI     ",
        "SRAI     ",
        "SLTI     ",
        "SLTIU    ",
        "LB       ",
        "LH       ",
        "LW       ",
        "LBU      ",
        "LHU      ",
        "SB       ",
        "SH       ",
        "SW       ",
        "BEQ      ",
        "BNE      ",
        "BLT      ",
        "BGE      ",
        "BLTU     ",
        "BGEU     ",
        "JAL      ",
        "JALR     ",
        "LUI      ",
        "AUIPC    "
        "MUL      ",
        "MULH     ",
        "MULHSU   ",
        "MULHU    ",
        "DIV      ",
        "DIVU     ",
        "REM      ",
        "REMU     ",

        "CSRRW    ",
        "CSRRS    ",
        "CSRRC    ",
        "CSRRWI   ",
        "CSRRSI   ",
        "CSRRCI   ",

        "ECALL    " ,
        "EBREAK   " ,
        "URET     " ,
        "SRET     " ,
        "HRET     " ,
        "MRET     " ,
        "DRET     " ,
        "SFENCE_VM" ,
        "SFENCE_VMA" ,
        "WFI      " ,

};
